baseurl: /
permalink: /:categories/:title/
markdown: rdiscount
excerpt_separator: ""
relative_permalinks: false
exclude: ["gruntfile.js","package.json","README.md","Rakefile","Procfile","Gemfile","Gemfile.lock","CNAME","config.rb","config.ru","scss","node_modules"]

prose:
  rooturl: 'announcements/_posts'
  siteurl: 'http://www.lifechurch.tv/'
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'announcement'
      - name: 'permalink'
        field:
          element: 'text'
          label: 'Permalink'
          value: ''
